### ISSUE TITLE
[android] Error when sharing a file from folder [app]/files/

### ISSUE THREAD

**Issue by vinayan3** [EstebanFuentealba/react-native-share#111]
I am using `react-native-fs` to save a file and on Android. The file path is like 
`file:///data/user/0/com.myapp.com/files/data_dump.json`.
I share it with
```
Share.open({url:fileURI, type: 'application/json'})
```
After that I get:
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'int android.database.Cursor.getColumnIndexOrThrow(java.lang.String)' on a null object reference
       at cl.json.ShareFile.getRealPathFromURI(ShareFile.java:102)
       at cl.json.ShareFile.isLocalFile(ShareFile.java:80)
       at cl.json.ShareFile.isFile(ShareFile.java:60)
       at cl.json.social.ShareIntent.open(ShareIntent.java:48)
       at cl.json.social.GenericShare.open(GenericShare.java:18)
       at cl.json.RNShareModule.open(RNShareModule.java:50)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:319)
       at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
       at android.os.Looper.loop(Looper.java:135)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
       at java.lang.Thread.run(Thread.java:818)
```

Everything works fine on iOS.

**Comment by ataillefer** [comment]
Very strange, sounds like #63 though you seem to run on a version that includes the merge.
Somehow the `type` property doesn't seem to be set when building the `ShareFile` instance.
Can you put a breakpoint in `RNShareModule` to check the passed options?

**Comment by vinayan3** [comment]
I manually set the `type` property and the app can now share a `json` or `csv` file out. For now this will work. I'll close this bug down then.

**Comment by vinayan3** [comment]
Actually another issue is that with files inside of an app like at `[app]/file` you can't share them without setting permissions. I've resorted to writing the file out to the external storage directory downloads folder and then sharing it.
