### ISSUE TITLE
NullPointerException on HTC M10

### ISSUE THREAD

**Issue by cipson** [EstebanFuentealba/react-native-share#131]
In HTC 10, i'm getting a null pointer exception for .lnk file
Looks like cursor and  cursor.moveToFirst() is checked before taking column index

```  E/unknown:React: Exception in native call
		   java.lang.NullPointerException: Attempt to invoke interface method 'int android.database.Cursor.getColumnIndexOrThrow(java.lang.String)' on a null object reference
			   at cl.json.ShareFile.getRealPathFromURI(ShareFile.java:102)
			   at cl.json.ShareFile.isLocalFile(ShareFile.java:80)
			   at cl.json.ShareFile.isFile(ShareFile.java:60)
			   at cl.json.social.ShareIntent.open(ShareIntent.java:48)
			   at cl.json.social.GenericShare.open(GenericShare.java:18)
			   at cl.json.RNShareModule.open(RNShareModule.java:50)
			   at java.lang.reflect.Method.invoke(Native Method)
			   at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:345)
			   at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:141)
			   at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
			   at android.os.Handler.handleCallback(Handler.java:739)
			   at android.os.Handler.dispatchMessage(Handler.java:95)
			   at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
			   at android.os.Looper.loop(Looper.java:168)
			   at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
			   at java.lang.Thread.run(Thread.java:818)
 E/unknown:React: Exception in native call
		   java.lang.NullPointerException: Attempt to invoke interface method 'int android.database.Cursor.getColumnIndexOrThrow(java.lang.String)' on a null object reference
			   at cl.json.ShareFile.getRealPathFromURI(ShareFile.java:102)
			   at cl.json.ShareFile.isLocalFile(ShareFile.java:80)
			   at cl.json.ShareFile.isFile(ShareFile.java:60)
			   at cl.json.social.ShareIntent.open(ShareIntent.java:48)
			   at cl.json.social.GenericShare.open(GenericShare.java:18)
			   at cl.json.RNShareModule.open(RNShareModule.java:50)
			   at java.lang.reflect.Method.invoke(Native Method)
			   at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:345)
			   at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:141)
			   at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
			   at android.os.Handler.handleCallback(Handler.java:739)
			   at android.os.Handler.dispatchMessage(Handler.java:95)
			   at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
			   at android.os.Looper.loop(Looper.java:168)
			   at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
			   at java.lang.Thread.run(Thread.java:818)
			   ```

**Comment by deepmehtait** [comment]
@cipson : Tested on HTC 10 and Samsung Note 5 its not crashing.

**Comment by ataillefer** [comment]
Looks similar to #63, are you passing the `type` as a parameter?

**Comment by deepmehtait** [comment]
@ataillefer : yes i tried latest 1.0.20 version and still was able to reproduce this issue. May be this cased is not yet addressed.
