### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException on ShareFile.java:63

### ISSUE THREAD

**Issue by jgcmarins** [EstebanFuentealba/react-native-share#167]
Guys, we're facing this error:
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
       at cl.json.ShareFile.isBase64File(ShareFile.java:63)
       at cl.json.ShareFile.isFile(ShareFile.java:60)
       at cl.json.social.ShareIntent.open(ShareIntent.java:48)
       at cl.json.social.GenericShare.open(GenericShare.java:18)
       at cl.json.RNShareModule.open(RNShareModule.java:50)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:363)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
       at android.os.Looper.loop(Looper.java:135)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by sibelius** [comment]
I think the error is here

https://github.com/EstebanFuentealba/react-native-share/blob/master/android/src/main/java/cl/json/ShareFile.java#L63

maybe getScheme() returns null

**Comment by sibelius** [comment]
https://developer.android.com/reference/android/net/Uri.html#getScheme()

`the scheme or null if this is a relative URI`

**Comment by jgcmarins** [comment]
#168
