### ISSUE TITLE
Issue using on Android

### ISSUE THREAD

**Issue by tgoldenberg** [EstebanFuentealba/react-native-share#31]
Followed the instructions and getting an error - `undefined is not an object (evaluating '_reactNativeShare2.default.open')`

**Comment by tgoldenberg** [comment]
Also when I `import` the module I get that it is `undefined`. However, all the installation instructions were followed

**Comment by tgoldenberg** [comment]
Think it may due to this error which loads when I run `react-native run-android` - 
```
[node-haste] Encountered an error while persisting cache:
> SyntaxError: /Users/thomasgoldenberg/Desktop/bhagavad_gita_app/gitaAndroid/node_modules/react-native-share/android/build/intermediates/exploded-aar/com.android.support/appcompat-v7/23.0.1/res/drawable-hdpi/abc_textfield_search_activated_mtrl_alpha.9.png: Unexpected character '�' (1:0)
> > 1 | �PNG
>     | ^
>   2 | 
>   3 | 
>   4 | IHD�¥�IDATWc```�O+#�P�
                              ��0Մ!�0O��j�UIEND�B`�
>     at Parser.pp.raise (/Users/thomasgoldenberg/Desktop/bhagavad_gita_app/gitaAndroid/node_modules/babylon/lib/parser/location.js:22:13)
>     at Parser.getTokenFromCode (/Users/thomasgoldenberg/Desktop/bhagavad_gita_app/gitaAndroid/node_modules/babylon/lib/tokenizer/index.js:561:12)
>     at Parser.readToken (/Users/thomasgoldenberg/Desktop/bhagavad_gita_app/gitaAndroid/node_modules/babylon/lib/tokenizer/index.js:180:21)
>     at Parser.<anonymous> (/Users/thomasgoldenberg/Desktop/bhagavad_gita_app/gitaAndroid/node_modules/babylon/lib/plugins/jsx/index.js:51:20)
>     at Parser.readToken (/Users/thomasgoldenberg/Desktop/bhagavad_gita_app/gitaAndroid/node_modules/babylon/lib/plugins/flow.js:155:22)
>     at Parser.nextToken (/Users/thomasgoldenberg/Desktop/bhagavad_gita_app/gitaAndroid/node_modules/babylon/lib/tokenizer/index.js:169:21)
>     at Parser.parse (/Users/thomasgoldenberg/Desktop/bhagavad_gita_app/gitaAndroid/node_modules/babylon/lib/parser/index.js:128:12)
>     at parse (/Users/thomasgoldenberg/Desktop/bhagavad_gita_app/gitaAndroid/node_modules/babylon/lib/index.js:47:47)
>     at File.parse (/Users/thomasgoldenberg/Desktop/bhagavad_gita_app/gitaAndroid/node_modules/babel-core/lib/transformation/file/index.js:517:34)
>     at File.parseCode (/Users/thomasgoldenberg/Desktop/bhagavad_gita_app/gitaAndroid/node_modules/babel-core/lib/transformation/file/index.js:603:20)
```

**Comment by tgoldenberg** [comment]
so I got it working now, but only by starting a new project and starting over from scratch. Still not sure what caused it, but hopefully other people don't run into this issue as well :)
